alertManager:
  mainYaml:
    receivers:
      - name: Default
      - name: Critical
        email_configs:
          - to: platform.team@organisation.com
            from: platform-sandbox@organisation.com
            smarthost: 'smtp.example.com:25'
            require_tls: false
            headers:
              subject: 'ARKHAM-DEV-KK {{ template "email.default.subject" . }}'
      - name: Watchdog